const { PrismaClient } = require('@prisma/client');
const { sendJobAlertEmail } = require('../../../lib/services/jobAlertEmailService');

const prisma = new PrismaClient();

/**
 * API Endpoint: Subscribe to Job Alerts
 * 
 * Creates a job alert subscription from the salary calculator
 * User will receive matching jobs via email
 * 
 * POST /api/salary-calculator/subscribe
 */
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { email, name, specialty, location, state, city, employerId } = req.body;

  // Validation
  if (!email || !specialty || !location) {
    return res.status(400).json({ 
      error: 'Missing required fields',
      message: 'Email, specialty, and location are required'
    });
  }

  // Basic email validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return res.status(400).json({ 
      error: 'Invalid email',
      message: 'Please enter a valid email address'
    });
  }

  try {
    // Check total number of active alerts for this email (5 max limit)
    const totalAlerts = await prisma.jobAlert.count({
      where: {
        email: email.toLowerCase().trim(),
        active: true
      }
    });

    if (totalAlerts >= 5) {
      // Fetch one existing alert to get the unsubscribe token for manage page
      const existingAlert = await prisma.jobAlert.findFirst({
        where: {
          email: email.toLowerCase().trim(),
          active: true
        },
        select: {
          unsubscribeToken: true
        }
      });

      await prisma.$disconnect();
      return res.status(400).json({
        error: 'Maximum alerts reached',
        message: 'You can have up to 5 active job alerts. Please manage your existing alerts to create new ones.',
        maxReached: true,
        manageToken: existingAlert?.unsubscribeToken || null
      });
    }

    // Check if this exact alert already exists (same email + specialty + location + employer)
    const existingAlert = await prisma.jobAlert.findFirst({
      where: {
        email: email.toLowerCase().trim(),
        specialty,
        location,
        employerId: employerId || null,
        active: true
      }
    });

    if (existingAlert) {
      // Already subscribed - send them a fresh email with current jobs
      console.log(`📧 Existing alert found (ID: ${existingAlert.id}), sending fresh job list...`);
      
      sendJobAlertEmail(existingAlert.id).catch(err => {
        console.error('Failed to send reminder email:', err);
      });
      
      return res.status(200).json({
        success: true,
        message: 'You are already subscribed to this job alert',
        alertId: existingAlert.id,
        isNew: false
      });
    }

    // Create new job alert
    console.log(`✨ Creating new job alert: ${specialty} in ${location} for ${email}${employerId ? ` (employer: ${employerId})` : ''}`);
    
    const jobAlert = await prisma.jobAlert.create({
      data: {
        email: email.toLowerCase().trim(),
        name: name?.trim() || null,
        specialty,
        location,
        state: state || null,
        city: city || null,
        employerId: employerId || null,
        source: 'salary-calculator',
        active: true
        // unsubscribeToken is auto-generated by default(cuid())
      }
    });

    console.log(`✅ Job alert created (ID: ${jobAlert.id}), state: ${state || 'null'}, city: ${city || 'null'}`);

    await prisma.$disconnect();

    // Send welcome email with matching jobs (async, don't wait)
    console.log(`📧 Sending welcome email to ${email}...`);
    sendJobAlertEmail(jobAlert.id).catch(err => {
      console.error('Failed to send welcome email:', err);
      // Don't fail the subscription if email fails
    });

    return res.status(201).json({
      success: true,
      message: 'Job alert created successfully',
      alertId: jobAlert.id,
      isNew: true,
      alert: {
        specialty: jobAlert.specialty,
        location: jobAlert.location
      }
    });

  } catch (error) {
    console.error('Error creating job alert:', error);
    await prisma.$disconnect();

    return res.status(500).json({
      error: 'Failed to create job alert',
      message: 'Something went wrong. Please try again.'
    });
  }
}

